### ISSUE TITLE
support for query parameters

### ISSUE THREAD

**Issue by imp-dev** [aaronshaf/xhr-interceptor#6]
Hi,
How do I use this with query params? I could not find and example. The following is my code that I would like to test:

`axios.get('http://myapi/Customers/findOne', {
    params: {
      filter: {
        where: {
          provider: 'facebook',
          provideruserid: '12345,
        },
      },
    },
  })`

**Comment by dey-dey** [comment]
@imp-dev if you mean you'd like to access params for the request just do it like so:

```
  it('with params', async function() {
    app.get('/user/:id', (req, res) => {
      console.log(req.params) // { id: '1' }
      res.json({
        user: { id: req.params.id }
      })
    })

    let response = await axios.get('/user/1')
    expect(response.data).toEqual({
      user: { id: '1' }
    })
  })
```

the docs could be more explicit! PRs welcome :)

if i'm mistaken lemme know!

**Comment by dey-dey** [comment]
@imp-dev closing this. Lemme know if I haven't addressed the issue
